services:
  - type: web
    name: backend
    env: node
    buildCommand: 'npm install'
    startCommand: 'node api/index.js'
    routes:
      - type: rewrite
        source: '/api/(.*)'
        destination: '/api/index.js'
